from random import choice

health_advice = [
    "Choose a small apple or a few slices of your favorite fruit.",
    "Snack on a handful of almonds (about 12 almonds).",
    "Enjoy a hard-boiled egg for a protein-packed snack.",
    "Try a small serving of Greek yogurt (plain, non-fat).",
    "Opt for a cup of air-popped popcorn.",
    "Have a small piece of dark chocolate (around 1 square).",
    "Snack on carrot sticks with a light dip like hummus.",
    "Savor a small bowl of mixed berries (strawberries, blueberries, etc.).",
    "Enjoy a rice cake with a thin spread of almond butter.",
    "Have a slice of turkey or ham wrapped around a pickle.",
    "Snack on cucumber slices with a dash of salt and pepper.",
    "Drink a cup of black coffee or herbal tea.",
    "Nibble on 1 ounce of low-fat cheese.",
    "Try a boiled shrimp with a little cocktail sauce.",
    "Indulge in a small serving of cottage cheese.",
    "Choose a small handful of sunflower seeds.",
    "Snack on a small orange or mandarin.",
    "Treat yourself to a low-calorie protein bar.",
    "Have a few slices of watermelon.",
    "Eat a small bowl of mixed nuts (unsalted).",
    "Enjoy a low-fat string cheese stick.",
    "Try a few baked tortilla chips with salsa.",
    "Go for a small portion of steamed edamame.",
    "Eat a small avocado with a sprinkle of salt.",
    "Have a cup of vegetable soup (broth-based).",
    "Savor a few pieces of dried fruit like apricots.",
    "Snack on cherry tomatoes with a bit of feta cheese.",
    "Enjoy a cup of miso soup.",
    "Opt for a small serving of grilled chicken breast.",
    "Snack on a handful of baby carrots with ranch dressing.",
    "Indulge in 1/2 cup of sliced strawberries.",
    "Have a small bowl of plain oatmeal.",
    "Enjoy a few crackers with cheese.",
    "Snack on an ounce of baked pita chips with hummus.",
    "Choose a small banana.",
    "Have a few whole wheat crackers with a thin spread of peanut butter.",
    "Snack on a small portion of trail mix.",
    "Enjoy a small serving of baked sweet potato fries.",
    "Snack on roasted chickpeas.",
    "Go for a few slices of turkey or chicken breast.",
    "Have a small serving of chia pudding.",
    "Enjoy a boiled egg with a pinch of salt and pepper.",
    "Treat yourself to a sugar-free jello cup.",
    "Savor a small handful of grapes.",
    "Enjoy a slice of watermelon with a squeeze of lime.",
    "Snack on a small cup of non-fat pudding.",
    "Try a small portion of tofu stir-fried with vegetables.",
    "Have a small serving of baked kale chips.",
    "Indulge in a mini low-fat muffin.",
    "Have a small serving of roasted nuts.",
    "Enjoy a small bowl of low-fat frozen yogurt.",
    "Go for a cucumber and tomato salad with a light dressing.",
    "Try a mini whole wheat pita with tzatziki sauce.",
    "Snack on a few slices of cantaloupe.",
    "Savor a small serving of protein-packed quinoa.",
    "Treat yourself to 2 rice cakes with a light spread of almond butter.",
    "Choose 1 ounce of dark chocolate-covered almonds.",
    "Have a small serving of roasted pumpkin seeds.",
    "Snack on a small portion of boiled corn on the cob.",
    "Go for a few slices of smoked salmon.",
    "Snack on a small portion of veggie sticks with a low-fat dip.",
    "Indulge in a small portion of sugar-free frozen fruit bars.",
    "Try a small portion of homemade vegetable chips.",
    "Enjoy a small serving of baked zucchini fries.",
    "Have a small scoop of sherbet.",
    "Try a small bowl of chia seed pudding.",
    "Snack on a small handful of mixed seeds.",
    "Treat yourself to a low-calorie smoothie made with almond milk.",
    "Enjoy a small portion of roasted cauliflower.",
    "Savor a few pieces of dark chocolate with sea salt.",
    "Snack on 1 tablespoon of peanut butter with carrot sticks.",
    "Try a small serving of roasted beets.",
    "Go for a few pieces of low-fat cheese with apple slices.",
    "Enjoy a handful of baby bell peppers.",
    "Savor a small serving of baked apples with cinnamon.",
    "Snack on a small serving of pickles.",
    "Have a small bowl of low-fat popcorn with a sprinkle of cheese.",
    "Enjoy a small portion of roasted turkey breast.",
    "Snack on a small bowl of low-fat cottage cheese with pineapple.",
    "Opt for a boiled egg with a slice of avocado.",
    "Treat yourself to a small portion of homemade granola.",
    "Snack on a few pieces of fresh pineapple.",
    "Indulge in a small bowl of low-fat yogurt with a drizzle of honey.",
    "Savor a small serving of roasted Brussels sprouts.",
    "Have a cup of low-sodium broth-based soup.",
    "Try a small serving of scrambled egg whites.",
    "Go for a small serving of roasted sweet potatoes.",
    "Snack on a small serving of tuna with mustard.",
    "Have a few crackers with low-fat cheese.",
    "Treat yourself to a small serving of dark chocolate mousse.",
    "Enjoy a few pieces of dried coconut flakes.",
    "Opt for a few baby carrots with hummus.",
    "Indulge in a small serving of tomato soup.",
    "Snack on a few slices of grilled chicken with avocado.",
    "Go for a small bowl of plain yogurt with a sprinkle of cinnamon.",
    "Savor a small portion of roasted vegetables.",
    "Snack on a few fresh figs.",
    "Have a small portion of protein-packed Greek yogurt.",
    "Try a small bowl of mixed greens with balsamic vinegar.",
    "Snack on a small portion of homemade apple chips.",
    "Enjoy a small portion of roasted squash.",
    "Treat yourself to a few pieces of sugar-free chocolate.",
    "Snack on 1/2 cup of watermelon chunks.",
    "Opt for a small serving of roasted chickpea snacks.",
    "Savor a small handful of pistachios.",
    "Enjoy a small portion of yogurt parfait with fruit.",
    "Snack on a few slices of roasted turkey with mustard.",
    "Treat yourself to 1 ounce of cheese crisps.",
    "Go for a small portion of homemade fruit salad.",
    "Snack on 1/2 a grapefruit with a sprinkle of sugar substitute.",
    "Indulge in a few pieces of chocolate-covered strawberries.",
    "Snack on a small portion of fresh celery with peanut butter."
]


def generate_random_health_advice():
    return choice(health_advice)